import { nohemi, nohemiLight } from "@/lib/fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Halmosi Kornél - Portfólió",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="hu">
      <body
        className={`${nohemi.variable} ${nohemiLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
