import { nohemi, nohemiLight } from "@/lib/fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nohemi.variable} ${nohemiLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
